// Auto-generated index file for Adaptiva Design System
// Generated by sync-design-system.ps1

// Types (from types.ts - canonical source)
export type { UploadedFile, TrainedModel } from './types';
// Re-export data quality types from utils (canonical source for these)
export type { DataQualityIssue, ColumnIssue, DataQualityReport } from './utils/dataQuality';

// UI Components
export * from './components/ui';

// Feature Components
export { DashboardLayout } from './components/DashboardLayout';
export type { NavigationItem, UserInfo, FileInfo } from './components/DashboardLayout';
export { DataPreview } from './components/DataPreview';
export { DataQualityBanner } from './components/DataQualityBanner';
export type { DataQualityBannerProps, BannerIssue } from './components/DataQualityBanner';
export { EmptyState } from './components/EmptyState';
export type { EmptyStateProps } from './components/EmptyState';
export { BrandLogo } from './components/BrandLogo';
export { UploadZone } from './components/UploadZone';
export type { UploadZoneProps, SampleDataset } from './components/UploadZone';

// Chart Components - Re-exported from features/charts
export { 
  ChartCard,
  ChartCreator,
  ChartGallery,
  ChartPreview,
  ChartSuggestions,
  ChartTypeSelector,
  PlotlyChartRenderer,
  createPlotlyJson,
} from '@features/charts';
export type { 
  ChartConfig, 
  ChartCreationConfig, 
  PlotlyJson,
  ChartType,
} from '@features/charts';

// Prediction Components - Re-exported from features/predictions
export { 
  ModelCreator,
  ModelCard,
  ModelTypeSelector,
  FeatureSelector,
  DataValidationWarning,
  EmptyPredictionsState,
  ModelVisualization,
  PredictionsView,
} from '@features/predictions';

// Utils (export functions, not types again)
export { analyzeDataQuality } from './utils/dataQuality';


