// Auto-generated index file for Adaptiva Design System
// Generated by sync-design-system.ps1

// Types (from types.ts - canonical source)
export type { UploadedFile, ChartConfig, TrainedModel } from './types';
// Re-export data quality types from utils (canonical source for these)
export type { DataQualityIssue, ColumnIssue, DataQualityReport } from './utils/dataQuality';

// UI Components
export * from './components/ui';

// Feature Components
export { DashboardLayout } from './components/DashboardLayout';
export { DataPreview } from './components/DataPreview';
export { DataQualityBanner } from './components/DataQualityBanner';
export { EmptyState } from './components/EmptyState';
export { UploadZone } from './components/UploadZone';

// Utils (export functions, not types again)
export { analyzeDataQuality } from './utils/dataQuality';
