# Adaptiva Design System Sync Script
# This script copies the design system from adaptiva-design to adaptiva-fe
# and handles import path transformations

param(
    [string]$DesignRepoPath = "..\adaptiva-design",
    [string]$TargetPath = ".\src\design-system",
    [switch]$DryRun = $false,
    [switch]$Verbose = $false
)

$ErrorActionPreference = "Stop"

# Colors for output
function Write-Success { param($msg) Write-Host $msg -ForegroundColor Green }
function Write-Info { param($msg) Write-Host $msg -ForegroundColor Cyan }
function Write-Warn { param($msg) Write-Host $msg -ForegroundColor Yellow }

Write-Info "=========================================="
Write-Info "  Adaptiva Design System Sync Script"
Write-Info "=========================================="
Write-Host ""

# Resolve paths
$DesignRepoPath = Resolve-Path $DesignRepoPath -ErrorAction SilentlyContinue
if (-not $DesignRepoPath) {
    Write-Error "Design repo not found. Please ensure adaptiva-design is at ..\adaptiva-design"
    exit 1
}

Write-Info "Source: $DesignRepoPath"
Write-Info "Target: $TargetPath"
Write-Host ""

if ($DryRun) {
    Write-Warn "[DRY RUN] No files will be modified"
    Write-Host ""
}

# Step 1: Clean target directory
if (Test-Path $TargetPath) {
    Write-Warn "Target directory exists. Cleaning..."
    if (-not $DryRun) {
        Remove-Item -Path $TargetPath -Recurse -Force
    }
}

# Step 2: Create directory structure
Write-Info "Creating directory structure..."
$directories = @(
    "$TargetPath\components\ui",
    "$TargetPath\components\charts",
    "$TargetPath\components\predictions",
    "$TargetPath\styles",
    "$TargetPath\utils"
)

foreach ($dir in $directories) {
    if (-not $DryRun) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    if ($Verbose) { Write-Host "  Created: $dir" }
}

# Step 3: Copy files
Write-Info "Copying files..."

# Copy UI components
$uiSource = Join-Path $DesignRepoPath "src\app\components\ui"
$uiDest = Join-Path $TargetPath "components\ui"
if (Test-Path $uiSource) {
    if (-not $DryRun) {
        Copy-Item -Path "$uiSource\*" -Destination $uiDest -Recurse -Force
    }
    Write-Success "  + Copied UI components"
}

# Copy styles
$stylesSource = Join-Path $DesignRepoPath "src\styles"
$stylesDest = Join-Path $TargetPath "styles"
if (Test-Path $stylesSource) {
    if (-not $DryRun) {
        Copy-Item -Path "$stylesSource\*" -Destination $stylesDest -Force
    }
    Write-Success "  + Copied styles"
}

# Copy feature components
$componentsToCopy = @(
    "DashboardLayout.tsx",
    "DataPreview.tsx",
    "DataQualityBanner.tsx",
    "EmptyState.tsx",
    "UploadZone.tsx"
)

foreach ($component in $componentsToCopy) {
    $source = Join-Path $DesignRepoPath "src\app\components\$component"
    $dest = Join-Path $TargetPath "components\$component"
    if (Test-Path $source) {
        if (-not $DryRun) {
            Copy-Item -Path $source -Destination $dest -Force
        }
        Write-Success "  + Copied $component"
    } else {
        Write-Warn "  - Not found: $component"
    }
}

# Copy charts folder
$chartsSource = Join-Path $DesignRepoPath "src\app\components\charts"
$chartsDest = Join-Path $TargetPath "components\charts"
if (Test-Path $chartsSource) {
    if (-not $DryRun) {
        Copy-Item -Path "$chartsSource\*" -Destination $chartsDest -Recurse -Force
    }
    Write-Success "  + Copied charts components"
}

# Copy predictions folder
$predictionsSource = Join-Path $DesignRepoPath "src\app\components\predictions"
$predictionsDest = Join-Path $TargetPath "components\predictions"
if (Test-Path $predictionsSource) {
    if (-not $DryRun) {
        Copy-Item -Path "$predictionsSource\*" -Destination $predictionsDest -Recurse -Force
    }
    Write-Success "  + Copied predictions components"
}

# Copy utils
$utilsSource = Join-Path $DesignRepoPath "src\app\utils\dataQuality.ts"
$utilsDest = Join-Path $TargetPath "utils\dataQuality.ts"
if (Test-Path $utilsSource) {
    if (-not $DryRun) {
        Copy-Item -Path $utilsSource -Destination $utilsDest -Force
    }
    Write-Success "  + Copied dataQuality.ts"
}

# Step 4: Generate index files
Write-Info "Generating index files..."

# UI components index
$uiIndexContent = @'
// Auto-generated index file for design system UI components
// Generated by sync-design-system.ps1

export * from './button';
export * from './card';
export * from './badge';
export * from './dialog';
export * from './dropdown-menu';
export * from './select';
export * from './slider';
export * from './switch';
export * from './tabs';
export * from './tooltip';
export * from './progress';
export * from './avatar';
export * from './input';
export * from './label';
export * from './checkbox';
export * from './table';
export * from './scroll-area';
export * from './separator';
export * from './sheet';
export * from './skeleton';
export * from './textarea';
export * from './toggle';
export * from './toggle-group';
export { cn } from './utils';
'@

if (-not $DryRun) {
    Set-Content -Path (Join-Path $TargetPath "components\ui\index.ts") -Value $uiIndexContent
}
Write-Success "  + Created components/ui/index.ts"

# Main design system index
$mainIndexContent = @'
// Auto-generated index file for Adaptiva Design System
// Generated by sync-design-system.ps1

// UI Components
export * from './components/ui';

// Feature Components
export { DashboardLayout } from './components/DashboardLayout';
export { DataPreview } from './components/DataPreview';
export { DataQualityBanner } from './components/DataQualityBanner';
export { EmptyState } from './components/EmptyState';
export { UploadZone } from './components/UploadZone';

// Utils
export * from './utils/dataQuality';
'@

if (-not $DryRun) {
    Set-Content -Path (Join-Path $TargetPath "index.ts") -Value $mainIndexContent
}
Write-Success "  + Created index.ts"

Write-Host ""
Write-Success "=========================================="
Write-Success "  Sync Complete!"
Write-Success "=========================================="
Write-Host ""
Write-Info "Next steps:"
Write-Host "1. Import design system styles in your main CSS"
Write-Host "2. Use components with: import { Button } from '@design/components/ui'"
Write-Host ""
